version: '3.8'
services:

  MackSimpleAI:
    container_name: MackSimpleAI
    build:
      context: .
      dockerfile: ./Dockerfile.dockerfile
    ports:
      - "8080:8080"
    expose:
      - 8080
    networks:
      - mynetwork


networks:
  mynetwork:
    external: true


