spring:
  application:
    name: MackRadio
  datasource:
    hikari:
      max-lifetime: 1800000
      connection-timeout: 30000
      idle-timeout: 1200000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://212.64.18.207:3306/video
    username: root
    password: your_password
  data:
    redis:
      database: 0
      host: 127.0.0.1
      lettuce:
        pool:
          max-active: 8
          max-wait: 1
          max-idle: 8
          min-idle: 0
      timeout: 0
server:
  port: 8080
  servlet:
    session:
      cookie:
        domain: localhost
        http-only: false
